# -*- coding: UTF-8 -*-


# This file was *autogenerated* from the file pythontex-files-Tarea09/sage_default_default.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0p9791609077659043 = RealNumber('0.9791609077659043'); _sage_const_0p430715356970999 = RealNumber('0.430715356970999'); _sage_const_1p5250083079649113 = RealNumber('1.5250083079649113'); _sage_const_0p061165657369748695 = RealNumber('0.061165657369748695'); _sage_const_2p7989027102112827 = RealNumber('2.7989027102112827'); _sage_const_0p5015548718775755 = RealNumber('0.5015548718775755'); _sage_const_1p912158417289881 = RealNumber('1.912158417289881'); _sage_const_0p24440901271557722 = RealNumber('0.24440901271557722'); _sage_const_0p8205530309864537 = RealNumber('0.8205530309864537'); _sage_const_0p42261180235811696 = RealNumber('0.42261180235811696'); _sage_const_1p914008178794904 = RealNumber('1.914008178794904'); _sage_const_0p17482280182386326 = RealNumber('0.17482280182386326'); _sage_const_3p0850261801730925 = RealNumber('3.0850261801730925'); _sage_const_1p0104522969296543 = RealNumber('1.0104522969296543'); _sage_const_0p15356067616723457 = RealNumber('0.15356067616723457'); _sage_const_1p7711019287922931 = RealNumber('1.7711019287922931'); _sage_const_2p0952887890653016 = RealNumber('2.0952887890653016'); _sage_const_0p03975209722972092 = RealNumber('0.03975209722972092'); _sage_const_2p514022662217597 = RealNumber('2.514022662217597'); _sage_const_0p6049726172196987 = RealNumber('0.6049726172196987'); _sage_const_p2 = RealNumber('.2')


import os
import sys
import codecs

if '--interactive' not in sys.argv[_sage_const_1 :]:
    if sys.version_info[_sage_const_0 ] == _sage_const_2 :
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr, 'strict')
    else:
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout.buffer, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr.buffer, 'strict')

if '/usr/share/texlive/texmf-dist/scripts/pythontex' and '/usr/share/texlive/texmf-dist/scripts/pythontex' not in sys.path:
    sys.path.append('/usr/share/texlive/texmf-dist/scripts/pythontex')
from pythontex_utils import PythonTeXUtils
pytex = PythonTeXUtils()

pytex.docdir = os.getcwd()
if os.path.isdir('.'):
    os.chdir('.')
    if os.getcwd() not in sys.path:
        sys.path.append(os.getcwd())
else:
    if len(sys.argv) < _sage_const_2  or sys.argv[_sage_const_1 ] != '--manual':
        sys.exit('Cannot find directory .')
if pytex.docdir not in sys.path:
    sys.path.append(pytex.docdir)

pytex.formatter = latex


pytex.id = 'sage_default_default'
pytex.family = 'sage'
pytex.session = 'default'
pytex.restart = 'default'

pytex.command = 'code'
pytex.set_context('')
pytex.args = ''
pytex.instance = '0'
pytex.line = '29'

print('=>PYTHONTEX:STDOUT#0#code#')
sys.stderr.write('=>PYTHONTEX:STDERR#0#code#\n')
pytex.before()
latex.matrix_delimiters("[", "]")
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '1'
pytex.line = '40'

print('=>PYTHONTEX:STDOUT#1#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#1#sub#\n')
pytex.before()
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '2'
pytex.line = '63'

print('=>PYTHONTEX:STDOUT#2#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#2#block#\n')
pytex.before()
n1 = vector(RR, [_sage_const_2 , _sage_const_2 , -_sage_const_1 ])
n2 = vector(RR, [_sage_const_1 , -_sage_const_1 , _sage_const_3 ])
vr = n1.cross_product(n2)

v1 = vr.normalized()
v2 = vector(RR, [vr[_sage_const_1 ], -vr[_sage_const_0 ], _sage_const_0 ]).normalized()
v3 = v1.cross_product(v2).normalized()
B = block_matrix([[v1.column(), v2.column(), v3.column()]])

square = matrix(RR, [[_sage_const_0 , _sage_const_2 , _sage_const_2 ], [_sage_const_0 , _sage_const_2 , -_sage_const_2 ], [_sage_const_0 , -_sage_const_2 , -_sage_const_2 ], [_sage_const_0 , -_sage_const_2 , _sage_const_2 ]]).T
squareB = [B * square.column(i) for i in range(_sage_const_4 )]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '3'
pytex.line = '77'

print('=>PYTHONTEX:STDOUT#3#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#3#i#\n')
pytex.before()
print(pytex.formatter(vr))
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '4'
pytex.line = '83'

print('=>PYTHONTEX:STDOUT#4#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#4#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(v1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(v2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(v3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(squareB[_sage_const_0 ])
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '5'
pytex.line = '110'

print('=>PYTHONTEX:STDOUT#5#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#5#block#\n')
pytex.before()
H=matrix(QQ,[[-_sage_const_1 ,-_sage_const_1 ,_sage_const_1 ,_sage_const_0 ,_sage_const_2 ],[_sage_const_2 ,_sage_const_0 ,_sage_const_1 ,_sage_const_1 ,_sage_const_0 ]])
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '6'
pytex.line = '113'

print('=>PYTHONTEX:STDOUT#6#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#6#i#\n')
pytex.before()
print(pytex.formatter(H))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '7'
pytex.line = '123'

print('=>PYTHONTEX:STDOUT#7#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#7#block#\n')
pytex.before()
HtI = block_matrix([[H.T, _sage_const_1 ]])
HtIr = HtI.echelon_form()
HtIr = copy(HtIr)
HtIr.subdivide(_sage_const_2 , _sage_const_2 )
A = HtIr.subdivision(_sage_const_1 , _sage_const_1 ).T
Ar = A.echelon_form()
v1 = A.column(_sage_const_0 )
v2 = A.column(_sage_const_1 )
v3 = A.column(_sage_const_2 )
w1 = v1
w2 = v2 - (((v2.dot_product(w1))/(w1.dot_product(w1))) * w1)
w3 = v3 - (((v3.dot_product(w1))/(w1.dot_product(w1))) * w1) - (((v3.dot_product(w2))/(w2.dot_product(w2))) * w2)
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '8'
pytex.line = '138'

print('=>PYTHONTEX:STDOUT#8#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#8#i#\n')
pytex.before()
print(pytex.formatter(HtI))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '9'
pytex.line = '138'

print('=>PYTHONTEX:STDOUT#9#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#9#i#\n')
pytex.before()
print(pytex.formatter(HtIr))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '10'
pytex.line = '142'

print('=>PYTHONTEX:STDOUT#10#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#10#i#\n')
pytex.before()
print(pytex.formatter(A))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '11'
pytex.line = '142'

print('=>PYTHONTEX:STDOUT#11#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#11#i#\n')
pytex.before()
print(pytex.formatter(Ar))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '12'
pytex.line = '147'

print('=>PYTHONTEX:STDOUT#12#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#12#i#\n')
pytex.before()
print(pytex.formatter(v1))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '13'
pytex.line = '147'

print('=>PYTHONTEX:STDOUT#13#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#13#i#\n')
pytex.before()
print(pytex.formatter(v2))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '14'
pytex.line = '147'

print('=>PYTHONTEX:STDOUT#14#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#14#i#\n')
pytex.before()
print(pytex.formatter(v3))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '15'
pytex.line = '149'

print('=>PYTHONTEX:STDOUT#15#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#15#i#\n')
pytex.before()
print(pytex.formatter(w1))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '16'
pytex.line = '150'

print('=>PYTHONTEX:STDOUT#16#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#16#i#\n')
pytex.before()
print(pytex.formatter(w2))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '17'
pytex.line = '151'

print('=>PYTHONTEX:STDOUT#17#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#17#i#\n')
pytex.before()
print(pytex.formatter(w3))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '18'
pytex.line = '159'

print('=>PYTHONTEX:STDOUT#18#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#18#block#\n')
pytex.before()
XY = matrix(RR,[[ _sage_const_0p9791609077659043  ,  -_sage_const_0p430715356970999  ],
                [ _sage_const_1p5250083079649113  ,  _sage_const_0p061165657369748695  ],
                [ _sage_const_2p7989027102112827  ,  -_sage_const_0p5015548718775755  ],
                [ _sage_const_1p912158417289881  ,  _sage_const_0p24440901271557722  ],
                [ _sage_const_0p8205530309864537  ,  -_sage_const_0p42261180235811696  ],
                [ _sage_const_1p914008178794904  ,  -_sage_const_0p17482280182386326  ],
                [ _sage_const_3p0850261801730925  ,  -_sage_const_1p0104522969296543  ],
                [ _sage_const_0p15356067616723457  ,  -_sage_const_1p7711019287922931  ],
                [ _sage_const_2p0952887890653016  ,  _sage_const_0p03975209722972092  ],
                [ _sage_const_2p514022662217597  ,  -_sage_const_0p6049726172196987  ]])

X = XY.column(_sage_const_0 )
Y = XY.column(_sage_const_1 )
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '19'
pytex.line = '177'

print('=>PYTHONTEX:STDOUT#19#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#19#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(set(XY.rows()))
print('=>PYTHONTEX:FIELD_DELIM#')
print(min(X)-_sage_const_p2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(max(X)+_sage_const_p2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(min(X)-_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(max(X)+_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(min(Y)-_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(max(Y)+_sage_const_2 )
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '20'
pytex.line = '197'

print('=>PYTHONTEX:STDOUT#20#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#20#block#\n')
pytex.before()
B = matrix([[_sage_const_1  for x in X],
[x for x in X],
[x**_sage_const_2  for x in X]]).T

C = (B.T*B)**-_sage_const_1  * B.T * Y
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '21'
pytex.line = '207'

print('=>PYTHONTEX:STDOUT#21#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#21#i#\n')
pytex.before()
print(pytex.formatter(B))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '22'
pytex.line = '221'

print('=>PYTHONTEX:STDOUT#22#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#22#i#\n')
pytex.before()
print(pytex.formatter(C))
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '23'
pytex.line = '225'

print('=>PYTHONTEX:STDOUT#23#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#23#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(set(XY.rows()))
print('=>PYTHONTEX:FIELD_DELIM#')
print(min(X)-_sage_const_p2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(max(X)+_sage_const_p2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(min(X)-_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(max(X)+_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(min(Y)-_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(max(Y)+_sage_const_2 )
pytex.after()


pytex.cleanup()

