## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file posibleParcial1.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_234 = Integer(234); _sage_const_43 = Integer(43); _sage_const_24 = Integer(24); _sage_const_23 = Integer(23); _sage_const_11 = Integer(11); _sage_const_26 = Integer(26); _sage_const_9 = Integer(9); _sage_const_17 = Integer(17); _sage_const_33 = Integer(33); _sage_const_22 = Integer(22); _sage_const_16 = Integer(16); _sage_const_13 = Integer(13); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_238 = Integer(238); _sage_const_246 = Integer(246); _sage_const_0 = Integer(0)## This file (posibleParcial1.sagetex.sage) was *autogenerated* from posibleParcial1.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('posibleParcial1', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_234 
_st_.blockbegin()
try:
 Mf = matrix(Zmod(_sage_const_43 ), [[_sage_const_24 , _sage_const_23 , _sage_const_11 , _sage_const_26 ], [_sage_const_9 , _sage_const_17 , _sage_const_33 , _sage_const_22 ], [_sage_const_16 , _sage_const_16 , _sage_const_13 , _sage_const_4 ]])
 Mfp = block_matrix([[Mf, _sage_const_1 ]])
 Mfr = Mfp.echelon_form()
except:
 _st_.goboom(_sage_const_238 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_246 
 _st_.inline(_sage_const_0 , latex(Mfp))
except:
 _st_.goboom(_sage_const_246 )
try:
 _st_.current_tex_line = _sage_const_246 
 _st_.inline(_sage_const_1 , latex(Mfr))
except:
 _st_.goboom(_sage_const_246 )
_st_.endofdoc()

