# -*- coding: UTF-8 -*-


# This file was *autogenerated* from the file pythontex-files-newton/sage_default_default.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_3p5 = RealNumber('3.5'); _sage_const_3 = Integer(3); _sage_const_0p5 = RealNumber('0.5'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_8 = Integer(8); _sage_const_23 = Integer(23)


import os
import sys
import codecs

if '--interactive' not in sys.argv[_sage_const_1 :]:
    if sys.version_info[_sage_const_0 ] == _sage_const_2 :
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr, 'strict')
    else:
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout.buffer, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr.buffer, 'strict')

if '/usr/share/texlive/texmf-dist/scripts/pythontex' and '/usr/share/texlive/texmf-dist/scripts/pythontex' not in sys.path:
    sys.path.append('/usr/share/texlive/texmf-dist/scripts/pythontex')
from pythontex_utils import PythonTeXUtils
pytex = PythonTeXUtils()

pytex.docdir = os.getcwd()
if os.path.isdir('.'):
    os.chdir('.')
    if os.getcwd() not in sys.path:
        sys.path.append(os.getcwd())
else:
    if len(sys.argv) < _sage_const_2  or sys.argv[_sage_const_1 ] != '--manual':
        sys.exit('Cannot find directory .')
if pytex.docdir not in sys.path:
    sys.path.append(pytex.docdir)

pytex.formatter = latex


pytex.id = 'sage_default_default'
pytex.family = 'sage'
pytex.session = 'default'
pytex.restart = 'default'

pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '0'
pytex.line = '26'

print('=>PYTHONTEX:STDOUT#0#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#0#block#\n')
pytex.before()
		__tmp__=var("x"); f = symbolic_expression(tan(x) - x/(x-_sage_const_1 )).function(x)
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '1'
pytex.line = '29'

print('=>PYTHONTEX:STDOUT#1#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#1#i#\n')
pytex.before()
print(pytex.formatter(plot(f(x), (x,-_sage_const_10 ,_sage_const_10 ))))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '2'
pytex.line = '38'

print('=>PYTHONTEX:STDOUT#2#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#2#block#\n')
pytex.before()
		__tmp__=var("x"); f = symbolic_expression(sin(x) * (x-_sage_const_1 )- cos(x)).function(x)
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '3'
pytex.line = '41'

print('=>PYTHONTEX:STDOUT#3#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#3#i#\n')
pytex.before()
print(pytex.formatter(plot(f(x), (x,-_sage_const_5 ,_sage_const_0 ))))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '4'
pytex.line = '42'

print('=>PYTHONTEX:STDOUT#4#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#4#i#\n')
pytex.before()
print(pytex.formatter(plot(f(x), (x,-_sage_const_3p5 ,-_sage_const_3 ))))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '5'
pytex.line = '43'

print('=>PYTHONTEX:STDOUT#5#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#5#i#\n')
pytex.before()
print(pytex.formatter(plot(f(x), (x,-_sage_const_1 ,-_sage_const_0p5 ))))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '6'
pytex.line = '48'

print('=>PYTHONTEX:STDOUT#6#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#6#block#\n')
pytex.before()
		a = -_sage_const_0p6 
		b = -_sage_const_0p5 
		a0 = a
		b0 = b
		c0 = (a0+b0)/_sage_const_2 
		
		a1 = a0
		b1 = c0
		c1 = (a1+b1)/_sage_const_2 
		
		a2 = c1
		b2 = b1
		c2 = (a2+b2)/_sage_const_2 
		
		a3 = a2
		b3 = c2
		c3 = (a3+b3)/_sage_const_2 
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '7'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#7#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#7#i#\n')
pytex.before()
print(pytex.formatter(c0))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '8'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#8#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#8#i#\n')
pytex.before()
print(pytex.formatter(f(a0)))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '9'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#9#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#9#i#\n')
pytex.before()
print(pytex.formatter(f(c0)))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '10'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#10#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#10#i#\n')
pytex.before()
print(pytex.formatter(f(b0)))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '11'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#11#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#11#i#\n')
pytex.before()
print(pytex.formatter(c1))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '12'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#12#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#12#i#\n')
pytex.before()
print(pytex.formatter(f(a1)))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '13'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#13#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#13#i#\n')
pytex.before()
print(pytex.formatter(f(c1)))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '14'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#14#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#14#i#\n')
pytex.before()
print(pytex.formatter(f(b1)))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '15'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#15#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#15#i#\n')
pytex.before()
print(pytex.formatter(c2))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '16'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#16#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#16#i#\n')
pytex.before()
print(pytex.formatter(f(a2)))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '17'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#17#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#17#i#\n')
pytex.before()
print(pytex.formatter(f(c2)))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '18'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#18#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#18#i#\n')
pytex.before()
print(pytex.formatter(f(b2)))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '19'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#19#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#19#i#\n')
pytex.before()
print(pytex.formatter(c3))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '20'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#20#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#20#i#\n')
pytex.before()
print(pytex.formatter(f(a3)))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '21'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#21#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#21#i#\n')
pytex.before()
print(pytex.formatter(f(c3)))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '22'
pytex.line = '76'

print('=>PYTHONTEX:STDOUT#22#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#22#i#\n')
pytex.before()
print(pytex.formatter(f(b3)))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '23'
pytex.line = '87'

print('=>PYTHONTEX:STDOUT#23#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#23#block#\n')
pytex.before()
		epsilon = _sage_const_10 **-_sage_const_8 
		cota = numerical_approx((log((b-a)/epsilon)/log(_sage_const_2 )) - _sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '24'
pytex.line = '91'

print('=>PYTHONTEX:STDOUT#24#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#24#i#\n')
pytex.before()
print(pytex.formatter(cota))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '25'
pytex.line = '94'

print('=>PYTHONTEX:STDOUT#25#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#25#block#\n')
pytex.before()
a0 = a
b0 = b
c0 = (a0+b0)/_sage_const_2 
N = _sage_const_23 
i = _sage_const_0 
while i <= N:
	if (f(a0)*f(c0) < _sage_const_0 ):
		b0 = c0
		c0 = (a0+b0)/_sage_const_2 
	else:
		a0 = c0
		c0 = (a0+b0)/_sage_const_2 
	i++
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '26'
pytex.line = '112'

print('=>PYTHONTEX:STDOUT#26#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#26#i#\n')
pytex.before()
print(pytex.formatter(N))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '27'
pytex.line = '112'

print('=>PYTHONTEX:STDOUT#27#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#27#i#\n')
pytex.before()
print(pytex.formatter(c0))
pytex.after()


pytex.cleanup()

