## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file Modelo.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_19 = Integer(19); _sage_const_23836 = Integer(23836); _sage_const_2 = Integer(2); _sage_const_30 = Integer(30); _sage_const_1 = Integer(1); _sage_const_15 = Integer(15); _sage_const_10 = Integer(10); _sage_const_20 = Integer(20); _sage_const_36 = Integer(36); _sage_const_41 = Integer(41); _sage_const_0 = Integer(0); _sage_const_48 = Integer(48); _sage_const_56 = Integer(56); _sage_const_59 = Integer(59); _sage_const_63 = Integer(63); _sage_const_3 = Integer(3); _sage_const_66 = Integer(66); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_69 = Integer(69); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_71 = Integer(71); _sage_const_9 = Integer(9); _sage_const_73 = Integer(73); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_77 = Integer(77); _sage_const_16 = Integer(16); _sage_const_17 = Integer(17); _sage_const_18 = Integer(18); _sage_const_81 = Integer(81); _sage_const_21 = Integer(21); _sage_const_88 = Integer(88); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_24 = Integer(24); _sage_const_96 = Integer(96); _sage_const_101 = Integer(101); _sage_const_104 = Integer(104); _sage_const_25 = Integer(25); _sage_const_108 = Integer(108); _sage_const_26 = Integer(26); _sage_const_111 = Integer(111); _sage_const_27 = Integer(27); _sage_const_28 = Integer(28); _sage_const_114 = Integer(114); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_128 = Integer(128); _sage_const_32 = Integer(32); _sage_const_33 = Integer(33); _sage_const_34 = Integer(34); _sage_const_35 = Integer(35)## This file (Modelo.sagetex.sage) was *autogenerated* from Modelo.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('Modelo', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_19 
_st_.blockbegin()
try:
 set_random_seed(_sage_const_23836 ) # Cambia este número por las 5 primeras cifras de tu DNI o NIE
 
 n1 = ZZ.random_element(_sage_const_2 **_sage_const_30 )
 x1 = ZZ.random_element(n1)
 while(gcd(x1,n1)!=_sage_const_1 ):
   x1 = ZZ.random_element(n1)
 a2 = ZZ.random_element(_sage_const_2 **_sage_const_15 )
 b2 = ZZ.random_element(_sage_const_2 **_sage_const_15 )
 m2 = gcd(a2,b2)*ZZ.random_element(_sage_const_2 **_sage_const_10 )
 p3 = ZZ.random_element(_sage_const_2 **_sage_const_20 ).next_prime()
 m31 = p3*ZZ.random_element(_sage_const_2 **_sage_const_15 )
 m32 = p3*ZZ.random_element(_sage_const_2 **_sage_const_15 )
 g3 = gcd(m31,m32)
 n3 = ZZ.random_element(m31*m32)
 a3 = Zmod(m31)(n3)
 b3 = Zmod(m32)(n3)
except:
 _st_.goboom(_sage_const_36 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_41 
 _st_.inline(_sage_const_0 , latex(x1))
except:
 _st_.goboom(_sage_const_41 )
try:
 _st_.current_tex_line = _sage_const_41 
 _st_.inline(_sage_const_1 , latex(n1))
except:
 _st_.goboom(_sage_const_41 )
_st_.current_tex_line = _sage_const_48 
_st_.blockbegin()
try:
 A = matrix(ZZ, [[x1], [n1]])
 Ap = block_matrix([[A, _sage_const_1 ]])
 Ar = Ap.echelon_form()
 Ar = copy(Ar)
 Ar.subdivide([], _sage_const_1 )
 S = Ar.subdivision(_sage_const_0 , _sage_const_1 )
 R = S * A
except:
 _st_.goboom(_sage_const_56 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_2 , latex(Ap))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_3 , latex(Ar))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_4 , latex(x1))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_5 , latex(n1))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_6 , latex(S))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_7 , latex(A))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_8 , latex(R))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_71 
 _st_.inline(_sage_const_9 , latex(x1))
except:
 _st_.goboom(_sage_const_71 )
try:
 _st_.current_tex_line = _sage_const_71 
 _st_.inline(_sage_const_10 , latex(n1))
except:
 _st_.goboom(_sage_const_71 )
try:
 _st_.current_tex_line = _sage_const_73 
 _st_.inline(_sage_const_11 , latex(S[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.current_tex_line = _sage_const_73 
 _st_.inline(_sage_const_12 , latex(A[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.current_tex_line = _sage_const_73 
 _st_.inline(_sage_const_13 , latex(S[_sage_const_0 ][_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.current_tex_line = _sage_const_73 
 _st_.inline(_sage_const_14 , latex(A[_sage_const_1 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.current_tex_line = _sage_const_73 
 _st_.inline(_sage_const_15 , latex(R[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.current_tex_line = _sage_const_77 
 _st_.inline(_sage_const_16 , latex(S[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_77 )
try:
 _st_.current_tex_line = _sage_const_77 
 _st_.inline(_sage_const_17 , latex(A[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_77 )
try:
 _st_.current_tex_line = _sage_const_77 
 _st_.inline(_sage_const_18 , latex(R[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_77 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_19 , latex(A[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_20 , latex(S[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_21 , latex(n1))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_88 
 _st_.inline(_sage_const_22 , latex(a2))
except:
 _st_.goboom(_sage_const_88 )
try:
 _st_.current_tex_line = _sage_const_88 
 _st_.inline(_sage_const_23 , latex(b2))
except:
 _st_.goboom(_sage_const_88 )
try:
 _st_.current_tex_line = _sage_const_88 
 _st_.inline(_sage_const_24 , latex(m2))
except:
 _st_.goboom(_sage_const_88 )
_st_.current_tex_line = _sage_const_96 
_st_.blockbegin()
try:
 A = matrix(ZZ, [[a2], [b2]])
 Ap = block_matrix([[A, _sage_const_1 ]])
 Ar = Ap.echelon_form()
 R = Ar[:, _sage_const_1 :] * A
except:
 _st_.goboom(_sage_const_101 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_25 , latex(Ap))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_26 , latex(Ar))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_111 
 _st_.inline(_sage_const_27 , latex(a2))
except:
 _st_.goboom(_sage_const_111 )
try:
 _st_.current_tex_line = _sage_const_111 
 _st_.inline(_sage_const_28 , latex(b2))
except:
 _st_.goboom(_sage_const_111 )
try:
 _st_.current_tex_line = _sage_const_114 
 _st_.inline(_sage_const_29 , latex(Ar[:, _sage_const_1 :]))
except:
 _st_.goboom(_sage_const_114 )
try:
 _st_.current_tex_line = _sage_const_114 
 _st_.inline(_sage_const_30 , latex(A))
except:
 _st_.goboom(_sage_const_114 )
try:
 _st_.current_tex_line = _sage_const_114 
 _st_.inline(_sage_const_31 , latex(R))
except:
 _st_.goboom(_sage_const_114 )
try:
 _st_.current_tex_line = _sage_const_128 
 _st_.inline(_sage_const_32 , latex(a3))
except:
 _st_.goboom(_sage_const_128 )
try:
 _st_.current_tex_line = _sage_const_128 
 _st_.inline(_sage_const_33 , latex(m31))
except:
 _st_.goboom(_sage_const_128 )
try:
 _st_.current_tex_line = _sage_const_128 
 _st_.inline(_sage_const_34 , latex(b3))
except:
 _st_.goboom(_sage_const_128 )
try:
 _st_.current_tex_line = _sage_const_128 
 _st_.inline(_sage_const_35 , latex(m32))
except:
 _st_.goboom(_sage_const_128 )
try:
 _st_.current_tex_line = _sage_const_128 
 _st_.inline(_sage_const_32 , latex(a3))
except:
 _st_.goboom(_sage_const_128 )
try:
 _st_.current_tex_line = _sage_const_128 
 _st_.inline(_sage_const_33 , latex(m31))
except:
 _st_.goboom(_sage_const_128 )
try:
 _st_.current_tex_line = _sage_const_128 
 _st_.inline(_sage_const_34 , latex(b3))
except:
 _st_.goboom(_sage_const_128 )
try:
 _st_.current_tex_line = _sage_const_128 
 _st_.inline(_sage_const_35 , latex(m32))
except:
 _st_.goboom(_sage_const_128 )
_st_.endofdoc()

