# -*- coding: UTF-8 -*-


# This file was *autogenerated* from the file pythontex-files-Tarea08/sage_default_default.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_0p5 = RealNumber('0.5'); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4)


import os
import sys
import codecs

if '--interactive' not in sys.argv[_sage_const_1 :]:
    if sys.version_info[_sage_const_0 ] == _sage_const_2 :
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr, 'strict')
    else:
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout.buffer, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr.buffer, 'strict')

if '/usr/share/texlive/texmf-dist/scripts/pythontex' and '/usr/share/texlive/texmf-dist/scripts/pythontex' not in sys.path:
    sys.path.append('/usr/share/texlive/texmf-dist/scripts/pythontex')
from pythontex_utils import PythonTeXUtils
pytex = PythonTeXUtils()

pytex.docdir = os.getcwd()
if os.path.isdir('.'):
    os.chdir('.')
    if os.getcwd() not in sys.path:
        sys.path.append(os.getcwd())
else:
    if len(sys.argv) < _sage_const_2  or sys.argv[_sage_const_1 ] != '--manual':
        sys.exit('Cannot find directory .')
if pytex.docdir not in sys.path:
    sys.path.append(pytex.docdir)

pytex.formatter = latex


pytex.id = 'sage_default_default'
pytex.family = 'sage'
pytex.session = 'default'
pytex.restart = 'default'

pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '0'
pytex.line = '33'

print('=>PYTHONTEX:STDOUT#0#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#0#block#\n')
pytex.before()
beta = _sage_const_2 *pi/_sage_const_5 
r = _sage_const_0p5 
RM = matrix(RR, [[cos(beta), -sin(beta)], [sin(beta), cos(beta)]])

V = [(RM**i * vector([_sage_const_0 , _sage_const_1 ]) * r) + vector([_sage_const_1 , _sage_const_3 ]) for i in range(_sage_const_5 )]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '1'
pytex.line = '41'

print('=>PYTHONTEX:STDOUT#1#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#1#i#\n')
pytex.before()
print(pytex.formatter(V))
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '2'
pytex.line = '45'

print('=>PYTHONTEX:STDOUT#2#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#2#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_0 ])
pytex.after()


pytex.cleanup()

