# -*- coding: UTF-8 -*-


# This file was *autogenerated* from the file pythontex-files-Ejercicios-Transformaciones-Afines-Resuelta/sage_default_default.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_180 = Integer(180); _sage_const_48 = Integer(48); _sage_const_39 = Integer(39); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_0p5 = RealNumber('0.5'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_00p5 = RealNumber('00.5')


import os
import sys
import codecs

if '--interactive' not in sys.argv[_sage_const_1 :]:
    if sys.version_info[_sage_const_0 ] == _sage_const_2 :
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr, 'strict')
    else:
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout.buffer, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr.buffer, 'strict')

if '/usr/share/texlive/texmf-dist/scripts/pythontex' and '/usr/share/texlive/texmf-dist/scripts/pythontex' not in sys.path:
    sys.path.append('/usr/share/texlive/texmf-dist/scripts/pythontex')
from pythontex_utils import PythonTeXUtils
pytex = PythonTeXUtils()

pytex.docdir = os.getcwd()
if os.path.isdir('.'):
    os.chdir('.')
    if os.getcwd() not in sys.path:
        sys.path.append(os.getcwd())
else:
    if len(sys.argv) < _sage_const_2  or sys.argv[_sage_const_1 ] != '--manual':
        sys.exit('Cannot find directory .')
if pytex.docdir not in sys.path:
    sys.path.append(pytex.docdir)

pytex.formatter = latex


pytex.id = 'sage_default_default'
pytex.family = 'sage'
pytex.session = 'default'
pytex.restart = 'default'

pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '0'
pytex.line = '81'

print('=>PYTHONTEX:STDOUT#0#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#0#block#\n')
pytex.before()
R = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_2 , _sage_const_1 , _sage_const_0 ], [-_sage_const_1 , _sage_const_0 , _sage_const_1 ]])
alpha = pi/_sage_const_6 
MRRg = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , cos(alpha), -sin(alpha)], [_sage_const_0 , sin(alpha), cos(alpha)]])

Mg = R * MRRg * R**-_sage_const_1 
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '1'
pytex.line = '105'

print('=>PYTHONTEX:STDOUT#1#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#1#i#\n')
pytex.before()
print(pytex.formatter(Mg))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '2'
pytex.line = '111'

print('=>PYTHONTEX:STDOUT#2#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#2#block#\n')
pytex.before()
R1 = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_4 , _sage_const_1 , _sage_const_0 ], [_sage_const_4 , _sage_const_0 , _sage_const_1 ]])

b = pi/_sage_const_3 
MRRg = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , cos(b), -sin(b)], [_sage_const_0 , sin(b), cos(b)]])

Mg1 = R1 * MRRg * R1**-_sage_const_1 

C = [Mg1**i * vector(RR, [_sage_const_1 , _sage_const_5 , _sage_const_4 ]) for i in range(_sage_const_6 )]
gC = [Mg * v for v in C]
gCo = (Mg * vector(RR, [_sage_const_1 , _sage_const_4 , _sage_const_4 ]))[_sage_const_1 :]

C = [v[_sage_const_1 :] for v in C]
gC = [v[_sage_const_1 :] for v in gC]
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '3'
pytex.line = '128'

print('=>PYTHONTEX:STDOUT#3#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#3#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(gC[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(gC[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(gC[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(gC[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(gC[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(gC[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(gCo)
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '4'
pytex.line = '170'

print('=>PYTHONTEX:STDOUT#4#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#4#block#\n')
pytex.before()
pr1 = vector(RR, [-_sage_const_1 , _sage_const_0 ])
pr2 = vector(RR, [_sage_const_2 , _sage_const_2 ])
vr = (pr2 - pr1)
u1 = vr.normalized()
u2 = vector(RR, [vr[_sage_const_1 ], -vr[_sage_const_0 ]]).normalized()

R = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [pr1[_sage_const_0 ], u1[_sage_const_0 ], u2[_sage_const_0 ]], [pr1[_sage_const_1 ], u1[_sage_const_1 ], u2[_sage_const_1 ]]])
MRRp = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_0 ]])
MRRs = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_0 , -_sage_const_1 ]])

Mp = R * MRRp * R**-_sage_const_1 
Ms = R * MRRs * R**-_sage_const_1 
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '5'
pytex.line = '187'

print('=>PYTHONTEX:STDOUT#5#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#5#i#\n')
pytex.before()
print(pytex.formatter(R))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '6'
pytex.line = '191'

print('=>PYTHONTEX:STDOUT#6#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#6#i#\n')
pytex.before()
print(pytex.formatter(Mp))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '7'
pytex.line = '195'

print('=>PYTHONTEX:STDOUT#7#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#7#i#\n')
pytex.before()
print(pytex.formatter(Ms))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '8'
pytex.line = '201'

print('=>PYTHONTEX:STDOUT#8#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#8#block#\n')
pytex.before()
R = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_3 , _sage_const_1 , _sage_const_0 ], [-_sage_const_3 , _sage_const_0 , _sage_const_1 ]])

a = pi/_sage_const_2 
MRRg = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , cos(a), -sin(a)], [_sage_const_0 , sin(a), cos(a)]])
Mg = R * MRRg * R**-_sage_const_1 

cp0 = vector(RR, [_sage_const_1 , _sage_const_4 , -_sage_const_2 ])

C = [Mg**i * cp0 for i in range(_sage_const_4 )]
sC = [Ms * v for v in C]
pC = [Mp * v for v in C]

C = [v[_sage_const_1 :] for v in C]
sC = [v[_sage_const_1 :] for v in sC]
pC = [v[_sage_const_1 :] for v in pC]
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '9'
pytex.line = '219'

print('=>PYTHONTEX:STDOUT#9#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#9#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(pr1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(pr2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(pr1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(pr1 + u1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(pr1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(pr1 + u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(sC[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(sC[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(sC[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(sC[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(pC[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(pC[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(pC[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(pC[_sage_const_3 ])
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '10'
pytex.line = '266'

print('=>PYTHONTEX:STDOUT#10#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#10#block#\n')
pytex.before()
R = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_1 , _sage_const_1 , _sage_const_0 ], [_sage_const_1 , _sage_const_0 , _sage_const_1 ]])
f = _sage_const_3 
MRRh = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , f, _sage_const_0 ], [_sage_const_0 , _sage_const_0 , f]])

Mf = R * MRRh * R**-_sage_const_1 

tp0 = vector(RR, [-_sage_const_4 , _sage_const_2 ])
tp1 = vector(RR, [-_sage_const_3 , _sage_const_2 ])
tsv = tp1 - tp0
tsmp = tp0 + tsv/_sage_const_2 
tp2 = tsmp + _sage_const_5  * vector(RR, [-tsv[_sage_const_1 ], tsv[_sage_const_0 ]]).normalized()

C = vector(RR, [_sage_const_1 , tp0[_sage_const_0 ], tp0[_sage_const_1 ]]), vector(RR, [_sage_const_1 , tp1[_sage_const_0 ], tp1[_sage_const_1 ]]), vector(RR, [_sage_const_1 , tp2[_sage_const_0 ], tp2[_sage_const_1 ]])
hC = [Mf * v for v in C]

C = [v[_sage_const_1 :] for v in C]
hC = [v[_sage_const_1 :] for v in hC]
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '11'
pytex.line = '286'

print('=>PYTHONTEX:STDOUT#11#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#11#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(hC[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(hC[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(hC[_sage_const_2 ])
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '12'
pytex.line = '321'

print('=>PYTHONTEX:STDOUT#12#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#12#block#\n')
pytex.before()
R = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_1 , _sage_const_1 , _sage_const_0 ], [_sage_const_3 , _sage_const_0 , _sage_const_1 ]])

a = pi/_sage_const_4 
MRRg = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , cos(a), -sin(a)], [_sage_const_0 , sin(a), cos(a)]])
Mg = R * MRRg * R**-_sage_const_1 

op0 = vector(RR, [_sage_const_1 , _sage_const_2 , _sage_const_5 ])

C = [Mg**i * op0 for i in range(_sage_const_8 )]
C = [v[_sage_const_1 :] for v in C]
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '13'
pytex.line = '334'

print('=>PYTHONTEX:STDOUT#13#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#13#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_6 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_7 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_6 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_7 ])
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '14'
pytex.line = '377'

print('=>PYTHONTEX:STDOUT#14#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#14#block#\n')
pytex.before()
R = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [-_sage_const_4 , _sage_const_1 , _sage_const_0 ], [-_sage_const_1 , _sage_const_0 , _sage_const_1 ]])

a = _sage_const_2 *pi/_sage_const_5 
MRRg = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , cos(a), -sin(a)], [_sage_const_0 , sin(a), cos(a)]])
Mg = R * MRRg * R**-_sage_const_1 

sp0 = vector(RR, [_sage_const_1 , -_sage_const_2 , _sage_const_0 ])

C = [Mg**i * sp0 for i in range(_sage_const_5 )]

R = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [-_sage_const_8 , _sage_const_1 , _sage_const_0 ], [_sage_const_4 , _sage_const_0 , _sage_const_1 ]])

a = pi/_sage_const_180  * _sage_const_48 
MRRg = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , cos(a), -sin(a)], [_sage_const_0 , sin(a), cos(a)]])
Mg = R * MRRg * R**-_sage_const_1 

Cp = [Mg * v for v in C]

C = [v[_sage_const_1 :] for v in C]
Cp = [v[_sage_const_1 :] for v in Cp]


pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '15'
pytex.line = '402'

print('=>PYTHONTEX:STDOUT#15#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#15#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(Cp[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(Cp[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(Cp[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(Cp[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(Cp[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(Cp[_sage_const_0 ])
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '16'
pytex.line = '461'

print('=>PYTHONTEX:STDOUT#16#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#16#block#\n')
pytex.before()
R = matrix(RR,[[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],
            [_sage_const_5 ,_sage_const_1 ,_sage_const_0 ],
            [_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]])
R.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '17'
pytex.line = '466'

print('=>PYTHONTEX:STDOUT#17#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#17#i#\n')
pytex.before()
print(pytex.formatter(R))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '18'
pytex.line = '469'

print('=>PYTHONTEX:STDOUT#18#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#18#block#\n')
pytex.before()
beta = _sage_const_2 *pi/_sage_const_5 
G = matrix(RR,[[_sage_const_1 , _sage_const_0      ,  _sage_const_0       ],
            [_sage_const_0 , cos(beta), -sin(beta)],
            [_sage_const_0 , sin(beta),  cos(beta)]])
g=R*G*R**-_sage_const_1 
g.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '19'
pytex.line = '477'

print('=>PYTHONTEX:STDOUT#19#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#19#i#\n')
pytex.before()
print(pytex.formatter(g))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '20'
pytex.line = '481'

print('=>PYTHONTEX:STDOUT#20#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#20#block#\n')
pytex.before()
V = [g**i*vector(RR,[_sage_const_1 ,_sage_const_6 ,_sage_const_0 ]) for i in range(_sage_const_5 )]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '21'
pytex.line = '484'

print('=>PYTHONTEX:STDOUT#21#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#21#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_0 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '22'
pytex.line = '485'

print('=>PYTHONTEX:STDOUT#22#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#22#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_1 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '23'
pytex.line = '486'

print('=>PYTHONTEX:STDOUT#23#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#23#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_2 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '24'
pytex.line = '487'

print('=>PYTHONTEX:STDOUT#24#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#24#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_3 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '25'
pytex.line = '488'

print('=>PYTHONTEX:STDOUT#25#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#25#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_4 ]))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '26'
pytex.line = '492'

print('=>PYTHONTEX:STDOUT#26#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#26#block#\n')
pytex.before()
R1 = matrix(RR,[[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],
             [_sage_const_1 ,_sage_const_1 ,_sage_const_0 ],
             [_sage_const_2 ,_sage_const_0 ,_sage_const_1 ]])
R1.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '27'
pytex.line = '498'

print('=>PYTHONTEX:STDOUT#27#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#27#i#\n')
pytex.before()
print(pytex.formatter(R1))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '28'
pytex.line = '500'

print('=>PYTHONTEX:STDOUT#28#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#28#block#\n')
pytex.before()
alpha = _sage_const_39 *pi/_sage_const_180 
G1 = matrix(RR,[[_sage_const_1 , _sage_const_0         ,  _sage_const_0         ],
            [_sage_const_0 , cos(alpha), -sin(alpha)],
            [_sage_const_0 , sin(alpha),  cos(alpha)]])
g1=R1*G1*R1**-_sage_const_1 
g1.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '29'
pytex.line = '508'

print('=>PYTHONTEX:STDOUT#29#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#29#i#\n')
pytex.before()
print(pytex.formatter(g1))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '30'
pytex.line = '512'

print('=>PYTHONTEX:STDOUT#30#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#30#block#\n')
pytex.before()
V1 = [g1*v for v in V]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '31'
pytex.line = '514'

print('=>PYTHONTEX:STDOUT#31#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#31#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_0 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '32'
pytex.line = '515'

print('=>PYTHONTEX:STDOUT#32#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#32#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_1 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '33'
pytex.line = '516'

print('=>PYTHONTEX:STDOUT#33#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#33#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_2 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '34'
pytex.line = '517'

print('=>PYTHONTEX:STDOUT#34#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#34#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_3 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '35'
pytex.line = '518'

print('=>PYTHONTEX:STDOUT#35#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#35#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_4 ]))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '36'
pytex.line = '522'

print('=>PYTHONTEX:STDOUT#36#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#36#block#\n')
pytex.before()
V = [v[_sage_const_1 :] for v in V]
V1 = [v[_sage_const_1 :] for v in V1]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '37'
pytex.line = '527'

print('=>PYTHONTEX:STDOUT#37#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#37#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_0 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '38'
pytex.line = '527'

print('=>PYTHONTEX:STDOUT#38#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#38#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_0 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '39'
pytex.line = '528'

print('=>PYTHONTEX:STDOUT#39#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#39#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_1 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '40'
pytex.line = '528'

print('=>PYTHONTEX:STDOUT#40#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#40#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_1 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '41'
pytex.line = '529'

print('=>PYTHONTEX:STDOUT#41#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#41#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_2 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '42'
pytex.line = '529'

print('=>PYTHONTEX:STDOUT#42#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#42#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_2 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '43'
pytex.line = '530'

print('=>PYTHONTEX:STDOUT#43#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#43#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_3 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '44'
pytex.line = '530'

print('=>PYTHONTEX:STDOUT#44#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#44#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_3 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '45'
pytex.line = '531'

print('=>PYTHONTEX:STDOUT#45#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#45#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_4 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '46'
pytex.line = '531'

print('=>PYTHONTEX:STDOUT#46#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#46#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_4 ]))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '47'
pytex.line = '535'

print('=>PYTHONTEX:STDOUT#47#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#47#block#\n')
pytex.before()
P=vector(RR,[_sage_const_1 ,_sage_const_2 ])
O1=vector(RR,[_sage_const_5 ,_sage_const_0 ])
g1O1=g1*vector(RR,[_sage_const_1 ,_sage_const_5 ,_sage_const_0 ])
g1O1=g1O1[_sage_const_1 :]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '48'
pytex.line = '540'

print('=>PYTHONTEX:STDOUT#48#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#48#i#\n')
pytex.before()
print(pytex.formatter(P))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '49'
pytex.line = '541'

print('=>PYTHONTEX:STDOUT#49#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#49#i#\n')
pytex.before()
print(pytex.formatter(O1))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '50'
pytex.line = '542'

print('=>PYTHONTEX:STDOUT#50#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#50#i#\n')
pytex.before()
print(pytex.formatter(g1O1))
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '51'
pytex.line = '571'

print('=>PYTHONTEX:STDOUT#51#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#51#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V1[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V1[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V1[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V1[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V1[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(P)
print('=>PYTHONTEX:FIELD_DELIM#')
print(O1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(P)
print('=>PYTHONTEX:FIELD_DELIM#')
print(g1O1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(P)
print('=>PYTHONTEX:FIELD_DELIM#')
print(P)
print('=>PYTHONTEX:FIELD_DELIM#')
print(O1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(g1O1)
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '52'
pytex.line = '597'

print('=>PYTHONTEX:STDOUT#52#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#52#block#\n')
pytex.before()
Pol = PolynomialRing(RR, names=('x', 'y',)); (x, y,) = Pol._first_ngens(2)
A=matrix(Pol,[[_sage_const_1 ,_sage_const_1 ,_sage_const_1 ],
            [x,_sage_const_1 ,_sage_const_5 ],
            [y,_sage_const_2 ,_sage_const_0 ]])
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '53'
pytex.line = '608'

print('=>PYTHONTEX:STDOUT#53#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#53#i#\n')
pytex.before()
print(pytex.formatter(det(A)))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '54'
pytex.line = '620'

print('=>PYTHONTEX:STDOUT#54#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#54#block#\n')
pytex.before()
B=g*vector(RR,[_sage_const_1 ,_sage_const_6 ,_sage_const_0 ])
B=B[_sage_const_1 :]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '55'
pytex.line = '623'

print('=>PYTHONTEX:STDOUT#55#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#55#i#\n')
pytex.before()
print(pytex.formatter(n(B)))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '56'
pytex.line = '628'

print('=>PYTHONTEX:STDOUT#56#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#56#block#\n')
pytex.before()
g1O1=g1*vector(RR,[_sage_const_1 ,_sage_const_5 ,_sage_const_0 ])
g1O1=g1O1[_sage_const_1 :]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '57'
pytex.line = '632'

print('=>PYTHONTEX:STDOUT#57#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#57#i#\n')
pytex.before()
print(pytex.formatter(n(g1O1)))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '58'
pytex.line = '637'

print('=>PYTHONTEX:STDOUT#58#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#58#block#\n')
pytex.before()
Bp=g1*g*vector(RR,[_sage_const_1 ,_sage_const_6 ,_sage_const_0 ])
Bp=Bp[_sage_const_1 :]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '59'
pytex.line = '642'

print('=>PYTHONTEX:STDOUT#59#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#59#i#\n')
pytex.before()
print(pytex.formatter(n(Bp)))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '60'
pytex.line = '673'

print('=>PYTHONTEX:STDOUT#60#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#60#block#\n')
pytex.before()
R = matrix(RR,[[ _sage_const_1 ,_sage_const_0 ,_sage_const_0 ],
            [ _sage_const_2 ,_sage_const_1 ,_sage_const_0 ],
            [-_sage_const_3 ,_sage_const_0 ,_sage_const_1 ]])
R.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '61'
pytex.line = '679'

print('=>PYTHONTEX:STDOUT#61#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#61#i#\n')
pytex.before()
print(pytex.formatter(R))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '62'
pytex.line = '683'

print('=>PYTHONTEX:STDOUT#62#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#62#block#\n')
pytex.before()
beta = _sage_const_2 *pi/_sage_const_5 
G = matrix(RR,[[_sage_const_1 , _sage_const_0         ,  _sage_const_0         ],
            [_sage_const_0 , cos(beta), -sin(beta)],
            [_sage_const_0 , sin(beta),  cos(beta)]])
g=R*G*R**-_sage_const_1 
g.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '63'
pytex.line = '691'

print('=>PYTHONTEX:STDOUT#63#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#63#i#\n')
pytex.before()
print(pytex.formatter(g))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '64'
pytex.line = '696'

print('=>PYTHONTEX:STDOUT#64#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#64#block#\n')
pytex.before()
V = [g**i*vector(RR,[_sage_const_1 ,_sage_const_3 ,-_sage_const_2 ]) for i in range(_sage_const_5 )]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '65'
pytex.line = '698'

print('=>PYTHONTEX:STDOUT#65#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#65#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_0 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '66'
pytex.line = '699'

print('=>PYTHONTEX:STDOUT#66#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#66#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_1 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '67'
pytex.line = '700'

print('=>PYTHONTEX:STDOUT#67#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#67#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_2 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '68'
pytex.line = '701'

print('=>PYTHONTEX:STDOUT#68#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#68#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_3 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '69'
pytex.line = '702'

print('=>PYTHONTEX:STDOUT#69#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#69#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_4 ]))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '70'
pytex.line = '708'

print('=>PYTHONTEX:STDOUT#70#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#70#block#\n')
pytex.before()
P=vector(RR,[-_sage_const_2 ,_sage_const_7 ])
Q=vector(RR,[_sage_const_0 ,_sage_const_9 ])
v1 = Q-P
v2=vector(RR,[-v1[_sage_const_1 ],v1[_sage_const_0 ]])
R=block_matrix(RR,[[       matrix([_sage_const_1 ,_sage_const_0 ,_sage_const_0 ])],
                [column_matrix([P,v1,v2])]])
R.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '71'
pytex.line = '717'

print('=>PYTHONTEX:STDOUT#71#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#71#i#\n')
pytex.before()
print(pytex.formatter(R))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '72'
pytex.line = '720'

print('=>PYTHONTEX:STDOUT#72#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#72#block#\n')
pytex.before()
sRR = matrix(RR,[[_sage_const_1 ,_sage_const_0 , _sage_const_0 ],
              [_sage_const_0 ,_sage_const_1 , _sage_const_0 ],
              [_sage_const_0 ,_sage_const_0 ,-_sage_const_1 ]])
sRR.subdivide(_sage_const_1 ,_sage_const_1 )
s=R*sRR*R**-_sage_const_1 
s.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '73'
pytex.line = '728'

print('=>PYTHONTEX:STDOUT#73#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#73#i#\n')
pytex.before()
print(pytex.formatter(sRR))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '74'
pytex.line = '728'

print('=>PYTHONTEX:STDOUT#74#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#74#i#\n')
pytex.before()
print(pytex.formatter(s))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '75'
pytex.line = '733'

print('=>PYTHONTEX:STDOUT#75#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#75#block#\n')
pytex.before()
V1 = [s*v for v in V]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '76'
pytex.line = '735'

print('=>PYTHONTEX:STDOUT#76#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#76#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_0 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '77'
pytex.line = '736'

print('=>PYTHONTEX:STDOUT#77#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#77#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_1 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '78'
pytex.line = '737'

print('=>PYTHONTEX:STDOUT#78#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#78#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_2 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '79'
pytex.line = '738'

print('=>PYTHONTEX:STDOUT#79#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#79#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_3 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '80'
pytex.line = '739'

print('=>PYTHONTEX:STDOUT#80#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#80#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_4 ]))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '81'
pytex.line = '743'

print('=>PYTHONTEX:STDOUT#81#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#81#block#\n')
pytex.before()
V = [vector(v[_sage_const_1 :]) for v in V]
V1 = [vector(v[_sage_const_1 :]) for v in V1]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '82'
pytex.line = '746'

print('=>PYTHONTEX:STDOUT#82#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#82#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_0 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '83'
pytex.line = '746'

print('=>PYTHONTEX:STDOUT#83#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#83#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_0 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '84'
pytex.line = '747'

print('=>PYTHONTEX:STDOUT#84#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#84#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_1 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '85'
pytex.line = '747'

print('=>PYTHONTEX:STDOUT#85#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#85#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_1 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '86'
pytex.line = '748'

print('=>PYTHONTEX:STDOUT#86#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#86#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_2 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '87'
pytex.line = '748'

print('=>PYTHONTEX:STDOUT#87#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#87#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_2 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '88'
pytex.line = '749'

print('=>PYTHONTEX:STDOUT#88#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#88#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_3 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '89'
pytex.line = '749'

print('=>PYTHONTEX:STDOUT#89#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#89#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_3 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '90'
pytex.line = '750'

print('=>PYTHONTEX:STDOUT#90#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#90#i#\n')
pytex.before()
print(pytex.formatter(V[_sage_const_4 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '91'
pytex.line = '750'

print('=>PYTHONTEX:STDOUT#91#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#91#i#\n')
pytex.before()
print(pytex.formatter(V1[_sage_const_4 ]))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '92'
pytex.line = '754'

print('=>PYTHONTEX:STDOUT#92#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#92#block#\n')
pytex.before()
O1=vector(RR,[_sage_const_2 ,-_sage_const_3 ])
sO1=s*vector(RR,[_sage_const_1 ,_sage_const_2 ,-_sage_const_3 ])
sO1=sO1[_sage_const_1 :]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '93'
pytex.line = '759'

print('=>PYTHONTEX:STDOUT#93#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#93#i#\n')
pytex.before()
print(pytex.formatter(O1))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '94'
pytex.line = '760'

print('=>PYTHONTEX:STDOUT#94#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#94#i#\n')
pytex.before()
print(pytex.formatter(sO1))
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '95'
pytex.line = '764'

print('=>PYTHONTEX:STDOUT#95#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#95#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V1[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V1[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V1[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V1[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(V1[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(O1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(sO1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(P)
print('=>PYTHONTEX:FIELD_DELIM#')
print(Q)
print('=>PYTHONTEX:FIELD_DELIM#')
print(P)
print('=>PYTHONTEX:FIELD_DELIM#')
print(Q)
print('=>PYTHONTEX:FIELD_DELIM#')
print(O1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(sO1)
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '96'
pytex.line = '816'

print('=>PYTHONTEX:STDOUT#96#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#96#block#\n')
pytex.before()
Pol = PolynomialRing(RR, names=('x', 'y',)); (x, y,) = Pol._first_ngens(2)
A=matrix(Pol,[[_sage_const_1 ,_sage_const_1 ,_sage_const_1 ],
            [x,-_sage_const_2 ,_sage_const_0 ],
            [y,_sage_const_7 ,_sage_const_9 ]])
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '97'
pytex.line = '827'

print('=>PYTHONTEX:STDOUT#97#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#97#i#\n')
pytex.before()
print(pytex.formatter(det(A)))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '98'
pytex.line = '838'

print('=>PYTHONTEX:STDOUT#98#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#98#block#\n')
pytex.before()
B=g*vector(RR,[_sage_const_1 ,_sage_const_3 ,-_sage_const_2 ])
B=B[_sage_const_1 :]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '99'
pytex.line = '841'

print('=>PYTHONTEX:STDOUT#99#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#99#i#\n')
pytex.before()
print(pytex.formatter(n(B)))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '100'
pytex.line = '846'

print('=>PYTHONTEX:STDOUT#100#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#100#block#\n')
pytex.before()
sO1=s*vector(RR,[_sage_const_1 ,_sage_const_2 ,-_sage_const_3 ])
sO1=sO1[_sage_const_1 :]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '101'
pytex.line = '850'

print('=>PYTHONTEX:STDOUT#101#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#101#i#\n')
pytex.before()
print(pytex.formatter(n(sO1)))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '102'
pytex.line = '855'

print('=>PYTHONTEX:STDOUT#102#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#102#block#\n')
pytex.before()
Bp=s*g*vector(RR,[_sage_const_1 ,_sage_const_3 ,-_sage_const_2 ])
Bp=Bp[_sage_const_1 :]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '103'
pytex.line = '860'

print('=>PYTHONTEX:STDOUT#103#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#103#i#\n')
pytex.before()
print(pytex.formatter(n(Bp)))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '104'
pytex.line = '876'

print('=>PYTHONTEX:STDOUT#104#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#104#block#\n')
pytex.before()
A = vector(RR, [_sage_const_1 , _sage_const_2 , -_sage_const_1 ])
B = vector(RR, [_sage_const_2 , _sage_const_1 , _sage_const_1 ])
C = vector(RR, [-_sage_const_1 , _sage_const_3 , _sage_const_1 ])

AB = B - A
AC = C - A
n = AB.cross_product(AC)

u1 = AB.normalized()
u2 = n.cross_product(AB)
u3 = n.normalized()

R = block_matrix(_sage_const_2 , _sage_const_1 , [matrix(RR, [_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]), column_matrix([A, u1, u2, u3])])
R.subdivide(_sage_const_1 , _sage_const_1 )

MRRs = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_0 , -_sage_const_1 ]])

Ms = R * MRRs * R**-_sage_const_1 
Ms.subdivide(_sage_const_1 , _sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '105'
pytex.line = '898'

print('=>PYTHONTEX:STDOUT#105#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#105#i#\n')
pytex.before()
print(pytex.formatter(Ms))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '106'
pytex.line = '914'

print('=>PYTHONTEX:STDOUT#106#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#106#block#\n')
pytex.before()
R = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ], [-_sage_const_2 , _sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_2 , _sage_const_0 , _sage_const_1 , _sage_const_0 ], [_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 ]])
f = _sage_const_1 /_sage_const_2 
MRRh = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , f, _sage_const_0 , _sage_const_0 ], [_sage_const_0 , _sage_const_0 , f, _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_0 , f]])
Mh = R * MRRh * R**-_sage_const_1 
Mh.subdivide(_sage_const_1 , _sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '107'
pytex.line = '922'

print('=>PYTHONTEX:STDOUT#107#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#107#i#\n')
pytex.before()
print(pytex.formatter(Mh))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '108'
pytex.line = '940'

print('=>PYTHONTEX:STDOUT#108#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#108#block#\n')
pytex.before()
n = vector(RR, [_sage_const_3 , _sage_const_1 , -_sage_const_1 ])
P = vector(RR, [_sage_const_1 , _sage_const_0 , _sage_const_2 ])
Q = vector(RR, [_sage_const_1 , _sage_const_1 , _sage_const_3 ])

PQ = Q - P

u1 = PQ.normalized()
u2 = PQ.cross_product(n).normalized()
u3 = n.normalized()

R = block_matrix(_sage_const_2 , _sage_const_1 , [matrix(RR, [_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]), column_matrix([P, u1, u2, u3])])
R.subdivide(_sage_const_1 , _sage_const_1 )

a = _sage_const_2 *pi/_sage_const_7 
MRRg = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , cos(a), -sin(a), _sage_const_0 ], [_sage_const_0 , sin(a), cos(a), _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ]])

Mg = R * MRRg * R**-_sage_const_1 

C = [Mg**i * vector(RR, [_sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_3 ]) for i in range(_sage_const_7 )]
W = [v[_sage_const_1 :] for v in C]
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '109'
pytex.line = '963'

print('=>PYTHONTEX:STDOUT#109#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#109#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(W[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(W[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(W[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(W[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(W[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(W[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(W[_sage_const_6 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(P+_sage_const_3 *u1+_sage_const_3 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(P+_sage_const_3 *u1-_sage_const_3 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(P-_sage_const_3 *u1-_sage_const_3 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(P-_sage_const_3 *u1+_sage_const_3 *u2)
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '110'
pytex.line = '1000'

print('=>PYTHONTEX:STDOUT#110#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#110#block#\n')
pytex.before()
D = vector(RR, [_sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_0 ]), vector(RR, [_sage_const_1 , _sage_const_2 , -_sage_const_1 , -_sage_const_3 ]), vector(RR, [_sage_const_1 , _sage_const_3 , -_sage_const_3 , -_sage_const_1 ]), vector(RR, [_sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_1 ]), vector(RR, [_sage_const_1 , _sage_const_4 , -_sage_const_6 , _sage_const_10 ]), vector(RR, [_sage_const_1 , _sage_const_5 , _sage_const_10 , -_sage_const_15 ])

n = vector(RR, [_sage_const_1 , _sage_const_1 , _sage_const_0 ])
v1 = vector(RR, [-n[_sage_const_1 ], n[_sage_const_0 ], _sage_const_0 ])
v2 = n.cross_product(v1)

u1, u2, u3 = v1.normalized(), v2.normalized(), n.normalized()

# x = 0, y = 1
R = block_matrix(_sage_const_2 , _sage_const_1 , [matrix(RR, [_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]), column_matrix(RR, [vector(RR, [_sage_const_0 , _sage_const_1 , _sage_const_0 ]), u1, u2, u3])])

MRRs = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 ],  [_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_0 , -_sage_const_1 ]])

Ms = R * MRRs * R**-_sage_const_1 

sime = [Ms * v for v in D]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '111'
pytex.line = '1021'

print('=>PYTHONTEX:STDOUT#111#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#111#i#\n')
pytex.before()
print(pytex.formatter(Ms))
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '112'
pytex.line = '1025'

print('=>PYTHONTEX:STDOUT#112#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#112#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_5 *u1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_5 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_5 *u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(D[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(D[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(D[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(D[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(D[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(D[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(sime[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(sime[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(sime[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(sime[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(sime[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(sime[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_16 *u1+_sage_const_16 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_16 *u1-_sage_const_16 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(-_sage_const_16 *u1-_sage_const_16 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(-_sage_const_16 *u1+_sage_const_16 *u2)
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '113'
pytex.line = '1073'

print('=>PYTHONTEX:STDOUT#113#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#113#block#\n')
pytex.before()
A = vector(RR, [_sage_const_1 , _sage_const_3 , -_sage_const_1 ])
B = vector(RR, [_sage_const_3 , _sage_const_2 , _sage_const_1 ])
AB = B - A
PM = A + (AB / _sage_const_2 )

n = AB
v1 = vector(RR, [-n[_sage_const_1 ], n[_sage_const_0 ], _sage_const_0 ])
v2 = n.cross_product(v1)


u1 = v1.normalized()
u2 = v2.normalized()
u3 = n.normalized()

R = block_matrix(_sage_const_2 , _sage_const_1 , [matrix(RR, [_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]), column_matrix([PM, u1, u2, u3])])

MRRs = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_0 , -_sage_const_1 ]])

Ms = R * MRRs * R**-_sage_const_1 
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '114'
pytex.line = '1095'

print('=>PYTHONTEX:STDOUT#114#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#114#i#\n')
pytex.before()
print(pytex.formatter(Ms))
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '115'
pytex.line = '1099'

print('=>PYTHONTEX:STDOUT#115#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#115#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(PM)
print('=>PYTHONTEX:FIELD_DELIM#')
print(PM+_sage_const_2 *u1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(PM)
print('=>PYTHONTEX:FIELD_DELIM#')
print(PM+_sage_const_2 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(PM)
print('=>PYTHONTEX:FIELD_DELIM#')
print(PM+_sage_const_2 *u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(A)
print('=>PYTHONTEX:FIELD_DELIM#')
print(B)
print('=>PYTHONTEX:FIELD_DELIM#')
print(PM)
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '116'
pytex.line = '1130'

print('=>PYTHONTEX:STDOUT#116#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#116#block#\n')
pytex.before()
# plano
pn = vector(RR, [_sage_const_1 , _sage_const_1 , _sage_const_2 ])
v1 = vector(RR, [-pn[_sage_const_1 ], pn[_sage_const_0 ], _sage_const_0 ])
v2 = pn.cross_product(v1)

A = vector(RR, [_sage_const_0p5 , _sage_const_0p1 , _sage_const_0p4 ])
Ah = vector(RR, [_sage_const_1 , _sage_const_00p5 , _sage_const_0p1 , _sage_const_0p4 ])

# proyectar A en la normal del plano obteniendo centro de cara
u1, u2, u3 = pn.normalized(), v1.normalized(), v2.normalized()
pB = column_matrix([u1, u2, u3])
MBBpv = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_0 ]])
Mpn = pB * MBBpv * pB**-_sage_const_1 
cO = Mpn * A

# rotar A en el centro de la cara obteniendo puntos de cara
cR = block_matrix(_sage_const_2 , _sage_const_1 , [matrix(RR, [_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]), column_matrix([cO, u2, u3, u1])])
a = _sage_const_2 *pi/_sage_const_5 
McRcRr = matrix(RR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , cos(a), -sin(a), _sage_const_0 ], [_sage_const_0 , sin(a), cos(a), _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ]])
Mcr = cR * McRcRr * cR**-_sage_const_1 
cAP = [Mcr**i * Ah for i in range(_sage_const_5 )]
cAP = [v[_sage_const_1 :] for v in cAP]

# simetria de cara por el plano obteniendo la otra cara
MBBsp = matrix(RR, [[-_sage_const_1 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_0 , _sage_const_1 ]])
Msp = pB * MBBsp * pB**-_sage_const_1 
cBP = [Msp * v for v in cAP]
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '117'
pytex.line = '1161'

print('=>PYTHONTEX:STDOUT#117#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#117#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_0p5 *u1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_0p5 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_0p5 *u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(cO)
print('=>PYTHONTEX:FIELD_DELIM#')
print(cO + _sage_const_0p5 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(cO)
print('=>PYTHONTEX:FIELD_DELIM#')
print(cO + _sage_const_0p5 *u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(cO)
print('=>PYTHONTEX:FIELD_DELIM#')
print(cO + _sage_const_0p5 *u1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(-_sage_const_0p5 *u2 -_sage_const_0p5 *u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_0p5 *u2 -_sage_const_0p5 *u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_0p5 *u2 +_sage_const_0p5 *u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(-_sage_const_0p5 *u2 +_sage_const_0p5 *u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cBP[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(cAP[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(A)
print('=>PYTHONTEX:FIELD_DELIM#')
print(cO)
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '118'
pytex.line = '1209'

print('=>PYTHONTEX:STDOUT#118#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#118#block#\n')
pytex.before()
P=vector(RR,[_sage_const_1 ,_sage_const_0 ,_sage_const_1 ])
v3 = vector(RR,[_sage_const_1 ,-_sage_const_1 ,_sage_const_1 ])
v1 = vector(RR,[_sage_const_1 ,_sage_const_1 ,_sage_const_0 ])
v2 = v1.cross_product(v3)
v1=v1/norm(v1)
v2=v2/norm(v2)
v3=v3/norm(v3)
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '119'
pytex.line = '1221'

print('=>PYTHONTEX:STDOUT#119#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#119#block#\n')
pytex.before()
R = block_matrix(RR,[[       matrix([_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ])],
                     [column_matrix([P,v1,v2,v3])]])
R.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '120'
pytex.line = '1226'

print('=>PYTHONTEX:STDOUT#120#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#120#i#\n')
pytex.before()
print(pytex.formatter(R))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '121'
pytex.line = '1231'

print('=>PYTHONTEX:STDOUT#121#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#121#block#\n')
pytex.before()
a = _sage_const_2 *pi/_sage_const_5 
G = column_matrix(RR,[[_sage_const_1 ,    _sage_const_0 ,     _sage_const_0 ,  _sage_const_0 ],
                     [_sage_const_0 ,cos(a),sin(a), _sage_const_0 ],
                     [_sage_const_0 ,-sin(a),cos(a),_sage_const_0 ],
                     [_sage_const_0 ,    _sage_const_0 ,     _sage_const_0 ,  _sage_const_1 ]])
g = R*G*R**-_sage_const_1 
g.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '122'
pytex.line = '1239'

print('=>PYTHONTEX:STDOUT#122#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#122#i#\n')
pytex.before()
print(pytex.formatter(g))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '123'
pytex.line = '1245'

print('=>PYTHONTEX:STDOUT#123#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#123#block#\n')
pytex.before()
puntogiro=R*vector(RR,[_sage_const_1 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ])
BasePiramideh = [g**i*puntogiro for i in range(_sage_const_5 )]
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '124'
pytex.line = '1252'

print('=>PYTHONTEX:STDOUT#124#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#124#block#\n')
pytex.before()
Verticeh = R*vector(RR,[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_5 ])
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '125'
pytex.line = '1258'

print('=>PYTHONTEX:STDOUT#125#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#125#block#\n')
pytex.before()
BP = [v[_sage_const_1 :] for v in BasePiramideh]
Vertice = Verticeh[_sage_const_1 :]
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '126'
pytex.line = '1262'

print('=>PYTHONTEX:STDOUT#126#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#126#i#\n')
pytex.before()
print(pytex.formatter(BP[_sage_const_0 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '127'
pytex.line = '1263'

print('=>PYTHONTEX:STDOUT#127#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#127#i#\n')
pytex.before()
print(pytex.formatter(BP[_sage_const_1 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '128'
pytex.line = '1264'

print('=>PYTHONTEX:STDOUT#128#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#128#i#\n')
pytex.before()
print(pytex.formatter(BP[_sage_const_2 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '129'
pytex.line = '1265'

print('=>PYTHONTEX:STDOUT#129#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#129#i#\n')
pytex.before()
print(pytex.formatter(BP[_sage_const_3 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '130'
pytex.line = '1266'

print('=>PYTHONTEX:STDOUT#130#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#130#i#\n')
pytex.before()
print(pytex.formatter(BP[_sage_const_4 ]))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '131'
pytex.line = '1268'

print('=>PYTHONTEX:STDOUT#131#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#131#i#\n')
pytex.before()
print(pytex.formatter(Vertice))
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '132'
pytex.line = '1296'

print('=>PYTHONTEX:STDOUT#132#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#132#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(Vertice)
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(Vertice)
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(Vertice)
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(Vertice)
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(Vertice)
print('=>PYTHONTEX:FIELD_DELIM#')
print(BP[_sage_const_0 ])
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '133'
pytex.line = '1334'

print('=>PYTHONTEX:STDOUT#133#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#133#block#\n')
pytex.before()
v3 = vector(RR,[_sage_const_2 ,-_sage_const_1 ,_sage_const_1 ])
v1 = vector(RR,[_sage_const_1 ,_sage_const_2 ,_sage_const_0 ])
v2 = v1.cross_product(v3)
v1=v1/norm(v1)
v2=v2/norm(v2)
v3=v3/norm(v3)
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '134'
pytex.line = '1345'

print('=>PYTHONTEX:STDOUT#134#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#134#block#\n')
pytex.before()
P = vector(RR,[_sage_const_1 ,_sage_const_1 ,_sage_const_0 ])
R = block_matrix(RR,[[       matrix([_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ])],
                     [column_matrix([P,v1,v2,v3])]])
R.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '135'
pytex.line = '1350'

print('=>PYTHONTEX:STDOUT#135#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#135#i#\n')
pytex.before()
print(pytex.formatter(R))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '136'
pytex.line = '1354'

print('=>PYTHONTEX:STDOUT#136#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#136#block#\n')
pytex.before()
a = _sage_const_2 *pi/_sage_const_6 
G = column_matrix(RR,[[_sage_const_1 ,    _sage_const_0 ,     _sage_const_0 ,  _sage_const_0 ],
                     [_sage_const_0 ,cos(a),sin(a), _sage_const_0 ],
                     [_sage_const_0 ,-sin(a),cos(a),_sage_const_0 ],
                     [_sage_const_0 ,    _sage_const_0 ,     _sage_const_0 ,  _sage_const_1 ]])
g = R*G*R**-_sage_const_1 
g.subdivide(_sage_const_1 ,_sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '137'
pytex.line = '1362'

print('=>PYTHONTEX:STDOUT#137#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#137#i#\n')
pytex.before()
print(pytex.formatter(g))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '138'
pytex.line = '1365'

print('=>PYTHONTEX:STDOUT#138#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#138#block#\n')
pytex.before()
BaseTorreh = [g**i*R*vector(RR,[_sage_const_1 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ]) for i in range(_sage_const_6 )]
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '139'
pytex.line = '1374'

print('=>PYTHONTEX:STDOUT#139#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#139#block#\n')
pytex.before()
TapaTorreh = [v+R*vector(RR,[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_3 ]) for v in BaseTorreh]
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '140'
pytex.line = '1380'

print('=>PYTHONTEX:STDOUT#140#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#140#block#\n')
pytex.before()
BT = [v[_sage_const_1 :] for v in BaseTorreh]
TT = [w[_sage_const_1 :] for w in TapaTorreh]
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '141'
pytex.line = '1412'

print('=>PYTHONTEX:STDOUT#141#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#141#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_3 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_4 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_5 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(TT[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(BT[_sage_const_0 ])
pytex.after()


pytex.cleanup()

