/*
Asignatura: (1903) Bases de Datos
Curso: 2024/25
Convocatoria: junio

Practica: P2. Consultas en SQL

Equipo de practicas: bdxxyy <----- PON TU CUENTA AQUI
 Integrante 1:              <----- NOMBRES COMPLETOS
 Integrante 2: 
*/

-- EJERCICIOS:

-- Q4

SELECT S.SERIE_ID, S.TITULO, S.GENERO
FROM SERIE S
WHERE S.SERIE_ID IN (
    SELECT DISTINCT N.SERIE
    FROM INTERES N
    WHERE N.USUARIO IN (
        SELECT U.USUARIO_ID
        FROM USUARIO U
        WHERE EXTRACT(YEAR FROM U.F_REGISTRO) = 2024
    )
    UNION
    SELECT E.SERIE
    FROM ESTOY_VIENDO E
    WHERE E.USUARIO IN (
        SELECT U.USUARIO_ID
        FROM USUARIO U
        WHERE U.CUOTA > 70
    )
);


-- Q5

SELECT S.SERIE_ID, S.TITULO, S.EDAD_MINIMA
FROM SERIE S
WHERE S.GENERO = 'Drama' AND EXISTS (
    SELECT *
    FROM INTERES N
    WHERE N.SERIE = S.SERIE_ID AND N.SERIE NOT IN (
        SELECT E.SERIE
        FROM ESTOY_VIENDO E
        WHERE E.USUARIO = N.USUARIO
    )
);

-- Q6


SELECT T.SERIE, COUNT(T.TEMPORADA) N_TEMPORADAS
FROM TEMPORADA T
WHERE T.SERIE IN (
    SELECT R.SERIE
    FROM REPARTO R
    WHERE R.INTERPRETE IN (
        SELECT I.INTERPRETE_ID
        FROM INTERPRETE I
        WHERE I.NACIONALIDAD = 'Reino Unido'
    )
    GROUP BY R.SERIE
    HAVING COUNT(*) > 5
)
GROUP BY SERIE
ORDER BY N_TEMPORADAS DESC;

