/*
Asignatura: (1903) Bases de Datos
Curso: 2024/25
Convocatoria: junio

Practica: P2. Consultas en SQL

Equipo de practicas: bd2215
 Integrante 1: Angel Ruiz Fernandez
 Integrante 2: 
*/

-- EJERCICIOS:

-- Q1

SELECT T.A_ESTRENO, S.TITULO TITULO_SERIE, COALESCE(C.TITULO, '****') TITULO_CAPITULO
FROM TEMPORADA T
JOIN CAPITULO C ON T.SERIE = C.SERIE AND C.TEMPORADA = 1
JOIN SERIE S ON S.SERIE_ID = T.SERIE
WHERE T.TEMPORADA = 1 AND C.CAPITULO = 1 AND C.SERIE IN (
    SELECT SERIE_ID
    FROM SERIE
    WHERE NACIONALIDAD = 'Reino Unido' OR NACIONALIDAD = 'Espana'
)
ORDER BY T.A_ESTRENO;

-- Q2

(SELECT INTERPRETE_ID FROM INTERPRETE I)
    MINUS
(
    (SELECT INTERPRETE_ID FROM INTERPRETE I WHERE I.NACIONALIDAD = 'Reino Unido')
        UNION
    (SELECT INTERPRETE_ID FROM INTERPRETE I WHERE I.A_NACIMIENTO <= 1982)
        UNION
    (SELECT INTERPRETE_ID
    FROM INTERPRETE I
    JOIN REPARTO R ON R.INTERPRETE = I.INTERPRETE_ID
    JOIN SERIE S ON S.SERIE_ID = R.SERIE
    WHERE S.GENERO = 'Drama')
);

-- Q3

SELECT U.NOMBRE NOMBRE_USUARIO, COALESCE(S.TITULO, '----') TITULO_SERIE
FROM USUARIO U
LEFT JOIN INTERES I ON I.USUARIO = U.USUARIO_ID
LEFT JOIN SERIE S ON S.SERIE_ID = I.SERIE
WHERE U.CUOTA < 50 AND U.F_REGISTRO < ADD_MONTHS(SYSDATE, -36)
ORDER BY U.NOMBRE, S.TITULO;
