## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file newton.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_18 = Integer(18); _sage_const_1 = Integer(1); _sage_const_20 = Integer(20); _sage_const_22 = Integer(22); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_30 = Integer(30); _sage_const_32 = Integer(32); _sage_const_34 = Integer(34); _sage_const_5 = Integer(5); _sage_const_35 = Integer(35); _sage_const_2 = Integer(2); _sage_const_3p5 = RealNumber('3.5'); _sage_const_3 = Integer(3); _sage_const_36 = Integer(36); _sage_const_0p5 = RealNumber('0.5'); _sage_const_40 = Integer(40); _sage_const_0p6 = RealNumber('0.6'); _sage_const_58 = Integer(58); _sage_const_69 = Integer(69); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_79 = Integer(79); _sage_const_82 = Integer(82); _sage_const_84 = Integer(84); _sage_const_16 = Integer(16); _sage_const_86 = Integer(86); _sage_const_23 = Integer(23); _sage_const_100 = Integer(100); _sage_const_105 = Integer(105); _sage_const_17 = Integer(17)## This file (newton.sagetex.sage) was *autogenerated* from newton.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('newton', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_18 
_st_.blockbegin()
try:
 __tmp__=var("x"); f = symbolic_expression(tan(x) - x/(x-_sage_const_1 )).function(x)
except:
 _st_.goboom(_sage_const_20 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_22 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(f(x), (x,-_sage_const_10 ,_sage_const_10 )))
except:
 _st_.goboom(_sage_const_22 )
_st_.current_tex_line = _sage_const_30 
_st_.blockbegin()
try:
 __tmp__=var("x"); f = symbolic_expression(sin(x) * (x-_sage_const_1 )- cos(x)).function(x)
except:
 _st_.goboom(_sage_const_32 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_34 
 _st_.plot(_sage_const_1 , format='notprovided', _p_=plot(f(x), (x,-_sage_const_5 ,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_34 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.plot(_sage_const_2 , format='notprovided', _p_=plot(f(x), (x,-_sage_const_3p5 ,-_sage_const_3 )))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_36 
 _st_.plot(_sage_const_3 , format='notprovided', _p_=plot(f(x), (x,-_sage_const_1 ,-_sage_const_0p5 )))
except:
 _st_.goboom(_sage_const_36 )
_st_.current_tex_line = _sage_const_40 
_st_.blockbegin()
try:
 a = -_sage_const_0p6 
 b = -_sage_const_0p5 
 a0 = a
 b0 = b
 c0 = (a0+b0)/_sage_const_2 
 
 a1 = a0
 b1 = c0
 c1 = (a1+b1)/_sage_const_2 
 
 a2 = c1
 b2 = b1
 c2 = (a2+b2)/_sage_const_2 
 
 a3 = a2
 b3 = c2
 c3 = (a3+b3)/_sage_const_2 
except:
 _st_.goboom(_sage_const_58 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_0 , latex(c0))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_1 , latex(f(a0)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_2 , latex(f(c0)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_3 , latex(f(b0)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_4 , latex(c1))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_5 , latex(f(a1)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_6 , latex(f(c1)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_7 , latex(f(b1)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_8 , latex(c2))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_9 , latex(f(a2)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_10 , latex(f(c2)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_11 , latex(f(b2)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_12 , latex(c3))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_13 , latex(f(a3)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_14 , latex(f(c3)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_15 , latex(f(b3)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_0 , latex(c0))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_1 , latex(f(a0)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_2 , latex(f(c0)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_3 , latex(f(b0)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_4 , latex(c1))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_5 , latex(f(a1)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_6 , latex(f(c1)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_7 , latex(f(b1)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_8 , latex(c2))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_9 , latex(f(a2)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_10 , latex(f(c2)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_11 , latex(f(b2)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_12 , latex(c3))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_13 , latex(f(a3)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_14 , latex(f(c3)))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_15 , latex(f(b3)))
except:
 _st_.goboom(_sage_const_69 )
_st_.current_tex_line = _sage_const_79 
_st_.blockbegin()
try:
 epsilon = _sage_const_10 **-_sage_const_8 
 cota = numerical_approx((log((b-a)/epsilon)/log(_sage_const_2 )) - _sage_const_1 )
except:
 _st_.goboom(_sage_const_82 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_84 
 _st_.inline(_sage_const_16 , latex(cota))
except:
 _st_.goboom(_sage_const_84 )
_st_.current_tex_line = _sage_const_86 
_st_.blockbegin()
try:
 a0 = a
 b0 = b
 c0 = (a0+b0)/_sage_const_2 
 N = _sage_const_23 
 i = _sage_const_0 
 while i <= N:
 if (f(a0)*f(c0) < _sage_const_0 ):
 b0 = c0
 c0 = (a0+b0)/_sage_const_2 
 else:
 a0 = c0
 c0 = (a0+b0)/_sage_const_2 
 i++
except:
 _st_.goboom(_sage_const_100 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_17 , latex(N))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_18 , latex(c0))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_17 , latex(N))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.inline(_sage_const_18 , latex(c0))
except:
 _st_.goboom(_sage_const_105 )
_st_.endofdoc()

