/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

class Bombilla {
    private int intensity;
    private boolean on;
    
    public boolean isOn() {
        return on;
    }

    public void encender() {
        on = true;
        intensity = 100;
    }

    public void apagar() {
        on = false;
        intensity = 0;
    }

    public int intensidad() {
        return intensity;
    }
};

public class App {

    public static void main(String[] args) {
        Bombilla b1, b2, b3;

        b1 = new Bombilla();
        b2 = new Bombilla();
        b3 = new Bombilla();

        b1.encender();
        System.out.println("intensidad: " + b1.intensidad());

    }
}
